export const TRIALTABLE_SET_FISHEYE_START = 'TRIALTABLE_SET_FISHEYE_START';
export const TRIALTABLE_SET_FISHEYE_SUCCESS = 'TRIALTABLE_SET_FISHEYE_SUCCESS';


export const setFishEye = (mode) => ({
  type: TRIALTABLE_SET_FISHEYE_SUCCESS,
  mode,
});
